import type { Metadata } from "next";
import { BottomNav } from '@/components/layout/BottomNav';
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-gradient-to-br from-violet-950 to-black">
          <main className="pb-20"> {/* Espace pour la navigation */}
            {children}
          </main>
          <BottomNav />
        </div>
      </body>
    </html>
  );
}